-- Create Standings Table
CREATE TABLE IF NOT EXISTS standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position INT,
    team_name TEXT NOT NULL,
    played INT DEFAULT 0,
    won INT DEFAULT 0,
    drawn INT DEFAULT 0,
    lost INT DEFAULT 0,
    goals_for INT DEFAULT 0,
    goals_against INT DEFAULT 0,
    goal_difference INT DEFAULT 0,
    points INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Create Fixtures/Results Table
CREATE TABLE IF NOT EXISTS fixtures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT,
    -- Storing as text for flexibility or TIMESTAMPTZ if specific
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    venue TEXT,
    time TEXT,
    competition TEXT DEFAULT 'FKF Division One',
    status TEXT CHECK (
        status IN ('Scheduled', 'Completed', 'Postponed')
    ),
    home_score INT,
    away_score INT,
    is_home_game BOOLEAN GENERATED ALWAYS AS (home_team ILIKE '%Hillside%') STORED,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Create Squad Table
CREATE TABLE IF NOT EXISTS squad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT,
    jersey_number TEXT,
    image_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Enable RLS
ALTER TABLE standings ENABLE ROW LEVEL SECURITY;
ALTER TABLE fixtures ENABLE ROW LEVEL SECURITY;
ALTER TABLE squad ENABLE ROW LEVEL SECURITY;
-- create policies
CREATE POLICY "Allow public read access on standings" ON standings FOR
SELECT USING (true);
CREATE POLICY "Allow public read access on fixtures" ON fixtures FOR
SELECT USING (true);
CREATE POLICY "Allow public read access on squad" ON squad FOR
SELECT USING (true);
-- Allow service role full access (implicit, but good to note, or explicit if needed)
-- We rely on service_role key for writes, which bypasses RLS by default in supabase-js if configured, 
-- but explicit policies for Authenticated roles could be added if we had auth users.